/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JTextPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import sudoku_solver.Logic.Coordinate;
import sudoku_solver.Logic.Puzzle;

/**
 *
 * @author cross
 */
public class UI extends javax.swing.JFrame {
    
    private Puzzle puzzle;

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        formatTextAreas();
        tryChangeTabBehaviour();
        setDialogPosition();
    }
    
    private void setDialogPosition() {
        int uiXpos = this.getLocation().x;
        int uiYpos = this.getLocation().y;
        int uiHeight = this.getSize().height;
        int uiWidth = this.getSize().width;
        int sdHeight = successDialog.getSize().height;
        int sdWidth = successDialog.getSize().width;
        int sdXpos = ((uiXpos + uiWidth)/2)-(sdWidth/2);
        int sdYpos = ((uiYpos + uiHeight)/2)-(sdHeight/2);
        successDialog.setLocation(sdXpos, sdYpos);
    }
    
    
    private void formatTextAreas() {
        // Change the font for text fields
        HashMap<Integer, javax.swing.JTextPane> fields = getCoordFields();
        Set<Integer> fieldKeys = fields.keySet();
        Font font = new Font("Verdana",Font.PLAIN, 25);
        for(int key : fieldKeys) {
            javax.swing.JTextPane field = fields.get(key);
            field.setFont(font);
            
            // try centerring
            StyledDocument doc = field.getStyledDocument();
            SimpleAttributeSet center = new SimpleAttributeSet();
            StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
            doc.setParagraphAttributes(0, doc.getLength(), center, false);
        }
    }
    
    private void tryChangeTabBehaviour() {
        HashMap<Integer, javax.swing.JTextPane> fields = getCoordFields();
        Set<Integer> fieldKeys = fields.keySet();
        for(int key : fieldKeys) {
            Component field = fields.get(key);
            field.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, null);
            field.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        successDialog = new javax.swing.JDialog();
        statusLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jScrollPane82 = new javax.swing.JScrollPane();
        coord1 = new javax.swing.JTextPane();
        jScrollPane83 = new javax.swing.JScrollPane();
        coord2 = new javax.swing.JTextPane();
        jScrollPane84 = new javax.swing.JScrollPane();
        coord3 = new javax.swing.JTextPane();
        jScrollPane85 = new javax.swing.JScrollPane();
        coord4 = new javax.swing.JTextPane();
        jScrollPane86 = new javax.swing.JScrollPane();
        coord5 = new javax.swing.JTextPane();
        jScrollPane87 = new javax.swing.JScrollPane();
        coord6 = new javax.swing.JTextPane();
        jScrollPane88 = new javax.swing.JScrollPane();
        coord7 = new javax.swing.JTextPane();
        jScrollPane89 = new javax.swing.JScrollPane();
        coord8 = new javax.swing.JTextPane();
        jScrollPane90 = new javax.swing.JScrollPane();
        coord9 = new javax.swing.JTextPane();
        jScrollPane91 = new javax.swing.JScrollPane();
        coord10 = new javax.swing.JTextPane();
        jScrollPane92 = new javax.swing.JScrollPane();
        coord11 = new javax.swing.JTextPane();
        jScrollPane93 = new javax.swing.JScrollPane();
        coord12 = new javax.swing.JTextPane();
        jScrollPane94 = new javax.swing.JScrollPane();
        coord13 = new javax.swing.JTextPane();
        jScrollPane95 = new javax.swing.JScrollPane();
        coord14 = new javax.swing.JTextPane();
        jScrollPane96 = new javax.swing.JScrollPane();
        coord15 = new javax.swing.JTextPane();
        jScrollPane97 = new javax.swing.JScrollPane();
        coord16 = new javax.swing.JTextPane();
        jScrollPane98 = new javax.swing.JScrollPane();
        coord17 = new javax.swing.JTextPane();
        jScrollPane99 = new javax.swing.JScrollPane();
        coord18 = new javax.swing.JTextPane();
        jScrollPane100 = new javax.swing.JScrollPane();
        coord19 = new javax.swing.JTextPane();
        jScrollPane101 = new javax.swing.JScrollPane();
        coord20 = new javax.swing.JTextPane();
        jScrollPane102 = new javax.swing.JScrollPane();
        coord21 = new javax.swing.JTextPane();
        jScrollPane103 = new javax.swing.JScrollPane();
        coord22 = new javax.swing.JTextPane();
        jScrollPane104 = new javax.swing.JScrollPane();
        coord23 = new javax.swing.JTextPane();
        jScrollPane105 = new javax.swing.JScrollPane();
        coord24 = new javax.swing.JTextPane();
        jScrollPane106 = new javax.swing.JScrollPane();
        coord25 = new javax.swing.JTextPane();
        jScrollPane107 = new javax.swing.JScrollPane();
        coord26 = new javax.swing.JTextPane();
        jScrollPane108 = new javax.swing.JScrollPane();
        coord27 = new javax.swing.JTextPane();
        jScrollPane109 = new javax.swing.JScrollPane();
        coord28 = new javax.swing.JTextPane();
        jScrollPane110 = new javax.swing.JScrollPane();
        coord29 = new javax.swing.JTextPane();
        jScrollPane111 = new javax.swing.JScrollPane();
        coord30 = new javax.swing.JTextPane();
        jScrollPane112 = new javax.swing.JScrollPane();
        coord31 = new javax.swing.JTextPane();
        jScrollPane113 = new javax.swing.JScrollPane();
        coord32 = new javax.swing.JTextPane();
        jScrollPane114 = new javax.swing.JScrollPane();
        coord33 = new javax.swing.JTextPane();
        jScrollPane115 = new javax.swing.JScrollPane();
        coord34 = new javax.swing.JTextPane();
        jScrollPane116 = new javax.swing.JScrollPane();
        coord35 = new javax.swing.JTextPane();
        jScrollPane117 = new javax.swing.JScrollPane();
        coord36 = new javax.swing.JTextPane();
        jScrollPane118 = new javax.swing.JScrollPane();
        coord37 = new javax.swing.JTextPane();
        jScrollPane119 = new javax.swing.JScrollPane();
        coord38 = new javax.swing.JTextPane();
        jScrollPane120 = new javax.swing.JScrollPane();
        coord39 = new javax.swing.JTextPane();
        jScrollPane121 = new javax.swing.JScrollPane();
        coord40 = new javax.swing.JTextPane();
        jScrollPane122 = new javax.swing.JScrollPane();
        coord41 = new javax.swing.JTextPane();
        jScrollPane123 = new javax.swing.JScrollPane();
        coord42 = new javax.swing.JTextPane();
        jScrollPane124 = new javax.swing.JScrollPane();
        coord43 = new javax.swing.JTextPane();
        jScrollPane125 = new javax.swing.JScrollPane();
        coord44 = new javax.swing.JTextPane();
        jScrollPane126 = new javax.swing.JScrollPane();
        coord45 = new javax.swing.JTextPane();
        jScrollPane127 = new javax.swing.JScrollPane();
        coord46 = new javax.swing.JTextPane();
        jScrollPane128 = new javax.swing.JScrollPane();
        coord47 = new javax.swing.JTextPane();
        jScrollPane129 = new javax.swing.JScrollPane();
        coord48 = new javax.swing.JTextPane();
        jScrollPane130 = new javax.swing.JScrollPane();
        coord49 = new javax.swing.JTextPane();
        jScrollPane131 = new javax.swing.JScrollPane();
        coord50 = new javax.swing.JTextPane();
        jScrollPane132 = new javax.swing.JScrollPane();
        coord51 = new javax.swing.JTextPane();
        jScrollPane133 = new javax.swing.JScrollPane();
        coord52 = new javax.swing.JTextPane();
        jScrollPane134 = new javax.swing.JScrollPane();
        coord53 = new javax.swing.JTextPane();
        jScrollPane135 = new javax.swing.JScrollPane();
        coord54 = new javax.swing.JTextPane();
        jScrollPane136 = new javax.swing.JScrollPane();
        coord55 = new javax.swing.JTextPane();
        jScrollPane137 = new javax.swing.JScrollPane();
        coord56 = new javax.swing.JTextPane();
        jScrollPane138 = new javax.swing.JScrollPane();
        coord57 = new javax.swing.JTextPane();
        jScrollPane139 = new javax.swing.JScrollPane();
        coord58 = new javax.swing.JTextPane();
        jScrollPane140 = new javax.swing.JScrollPane();
        coord59 = new javax.swing.JTextPane();
        jScrollPane141 = new javax.swing.JScrollPane();
        coord60 = new javax.swing.JTextPane();
        jScrollPane142 = new javax.swing.JScrollPane();
        coord61 = new javax.swing.JTextPane();
        jScrollPane143 = new javax.swing.JScrollPane();
        coord62 = new javax.swing.JTextPane();
        jScrollPane144 = new javax.swing.JScrollPane();
        coord63 = new javax.swing.JTextPane();
        jScrollPane145 = new javax.swing.JScrollPane();
        coord64 = new javax.swing.JTextPane();
        jScrollPane146 = new javax.swing.JScrollPane();
        coord65 = new javax.swing.JTextPane();
        jScrollPane147 = new javax.swing.JScrollPane();
        coord66 = new javax.swing.JTextPane();
        jScrollPane148 = new javax.swing.JScrollPane();
        coord67 = new javax.swing.JTextPane();
        jScrollPane149 = new javax.swing.JScrollPane();
        coord68 = new javax.swing.JTextPane();
        jScrollPane150 = new javax.swing.JScrollPane();
        coord69 = new javax.swing.JTextPane();
        jScrollPane151 = new javax.swing.JScrollPane();
        coord70 = new javax.swing.JTextPane();
        jScrollPane152 = new javax.swing.JScrollPane();
        coord71 = new javax.swing.JTextPane();
        jScrollPane153 = new javax.swing.JScrollPane();
        coord72 = new javax.swing.JTextPane();
        jScrollPane154 = new javax.swing.JScrollPane();
        coord73 = new javax.swing.JTextPane();
        jScrollPane155 = new javax.swing.JScrollPane();
        coord74 = new javax.swing.JTextPane();
        jScrollPane156 = new javax.swing.JScrollPane();
        coord75 = new javax.swing.JTextPane();
        jScrollPane157 = new javax.swing.JScrollPane();
        coord76 = new javax.swing.JTextPane();
        jScrollPane158 = new javax.swing.JScrollPane();
        coord77 = new javax.swing.JTextPane();
        jScrollPane159 = new javax.swing.JScrollPane();
        coord78 = new javax.swing.JTextPane();
        jScrollPane160 = new javax.swing.JScrollPane();
        coord79 = new javax.swing.JTextPane();
        jScrollPane161 = new javax.swing.JScrollPane();
        coord80 = new javax.swing.JTextPane();
        jScrollPane162 = new javax.swing.JScrollPane();
        coord81 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        devMenu = new javax.swing.JMenu();
        initTestPuzzleMenuItem = new javax.swing.JMenuItem();
        debugMenuItem = new javax.swing.JMenuItem();
        comingSoonMenu = new javax.swing.JMenu();
        autoGenMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        aboutLabel = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        successDialog.setMinimumSize(new java.awt.Dimension(200, 100));

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Successfully solved!");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        okButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                okButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout successDialogLayout = new javax.swing.GroupLayout(successDialog.getContentPane());
        successDialog.getContentPane().setLayout(successDialogLayout);
        successDialogLayout.setHorizontalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(successDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(successDialogLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(okButton)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        successDialogLayout.setVerticalGroup(
            successDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, successDialogLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addGap(79, 79, 79))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane82.setViewportView(coord1);

        jScrollPane83.setViewportView(coord2);

        jScrollPane84.setViewportView(coord3);

        jScrollPane85.setViewportView(coord4);

        jScrollPane86.setViewportView(coord5);

        jScrollPane87.setViewportView(coord6);

        jScrollPane88.setViewportView(coord7);

        jScrollPane89.setViewportView(coord8);

        jScrollPane90.setViewportView(coord9);

        jScrollPane91.setViewportView(coord10);

        jScrollPane92.setViewportView(coord11);

        jScrollPane93.setViewportView(coord12);

        jScrollPane94.setViewportView(coord13);

        jScrollPane95.setViewportView(coord14);

        jScrollPane96.setViewportView(coord15);

        jScrollPane97.setViewportView(coord16);

        jScrollPane98.setViewportView(coord17);

        jScrollPane99.setViewportView(coord18);

        jScrollPane100.setViewportView(coord19);

        jScrollPane101.setViewportView(coord20);

        jScrollPane102.setViewportView(coord21);

        jScrollPane103.setViewportView(coord22);

        jScrollPane104.setViewportView(coord23);

        jScrollPane105.setViewportView(coord24);

        jScrollPane106.setViewportView(coord25);

        jScrollPane107.setViewportView(coord26);

        jScrollPane108.setViewportView(coord27);

        jScrollPane109.setViewportView(coord28);

        jScrollPane110.setViewportView(coord29);

        jScrollPane111.setViewportView(coord30);

        jScrollPane112.setViewportView(coord31);

        jScrollPane113.setViewportView(coord32);

        jScrollPane114.setViewportView(coord33);

        jScrollPane115.setViewportView(coord34);

        jScrollPane116.setViewportView(coord35);

        jScrollPane117.setViewportView(coord36);

        jScrollPane118.setViewportView(coord37);

        jScrollPane119.setViewportView(coord38);

        jScrollPane120.setViewportView(coord39);

        jScrollPane121.setViewportView(coord40);

        jScrollPane122.setViewportView(coord41);

        jScrollPane123.setViewportView(coord42);

        jScrollPane124.setViewportView(coord43);

        jScrollPane125.setViewportView(coord44);

        jScrollPane126.setViewportView(coord45);

        jScrollPane127.setViewportView(coord46);

        jScrollPane128.setViewportView(coord47);

        jScrollPane129.setViewportView(coord48);

        jScrollPane130.setViewportView(coord49);

        jScrollPane131.setViewportView(coord50);

        jScrollPane132.setViewportView(coord51);

        jScrollPane133.setViewportView(coord52);

        jScrollPane134.setViewportView(coord53);

        jScrollPane135.setViewportView(coord54);

        jScrollPane136.setViewportView(coord55);

        jScrollPane137.setViewportView(coord56);

        jScrollPane138.setViewportView(coord57);

        jScrollPane139.setViewportView(coord58);

        jScrollPane140.setViewportView(coord59);

        jScrollPane141.setViewportView(coord60);

        jScrollPane142.setViewportView(coord61);

        jScrollPane143.setViewportView(coord62);

        jScrollPane144.setViewportView(coord63);

        jScrollPane145.setViewportView(coord64);

        jScrollPane146.setViewportView(coord65);

        jScrollPane147.setViewportView(coord66);

        jScrollPane148.setViewportView(coord67);

        jScrollPane149.setViewportView(coord68);

        jScrollPane150.setViewportView(coord69);

        jScrollPane151.setViewportView(coord70);

        jScrollPane152.setViewportView(coord71);

        jScrollPane153.setViewportView(coord72);

        jScrollPane154.setViewportView(coord73);

        jScrollPane155.setViewportView(coord74);

        jScrollPane156.setViewportView(coord75);

        jScrollPane157.setViewportView(coord76);

        jScrollPane158.setViewportView(coord77);

        jScrollPane159.setViewportView(coord78);

        jScrollPane160.setViewportView(coord79);

        jScrollPane161.setViewportView(coord80);

        jScrollPane162.setViewportView(coord81);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("(Ctrl + S to solve)");

        optionsMenu.setMnemonic('O');
        optionsMenu.setText("Options");

        newGameMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newGameMenuItem.setMnemonic('N');
        newGameMenuItem.setText("New Game");
        newGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuItemActionPerformed(evt);
            }
        });
        optionsMenu.add(newGameMenuItem);

        menu.add(optionsMenu);

        toolsMenu.setMnemonic('T');
        toolsMenu.setText("Tools");
        toolsMenu.setToolTipText("");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('S');
        jMenuItem4.setText("Solve");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        toolsMenu.add(jMenuItem4);
        toolsMenu.add(jSeparator1);

        devMenu.setMnemonic('D');
        devMenu.setText("Developer");

        initTestPuzzleMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        initTestPuzzleMenuItem.setMnemonic('I');
        initTestPuzzleMenuItem.setText("Initialize Test Puzzle");
        initTestPuzzleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTestPuzzleMenuItemActionPerformed(evt);
            }
        });
        devMenu.add(initTestPuzzleMenuItem);

        debugMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        debugMenuItem.setMnemonic('D');
        debugMenuItem.setText("Toggle Debug (enable)");
        debugMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugMenuItemActionPerformed(evt);
            }
        });
        devMenu.add(debugMenuItem);

        toolsMenu.add(devMenu);

        menu.add(toolsMenu);

        comingSoonMenu.setMnemonic('S');
        comingSoonMenu.setText("Coming Soon");

        autoGenMenuItem.setText("Auto-Generate Game");
        comingSoonMenu.add(autoGenMenuItem);

        menu.add(comingSoonMenu);

        helpMenu.setMnemonic('H');
        helpMenu.setText("Help");

        jMenuItem3.setMnemonic('H');
        jMenuItem3.setText("How To Play");
        helpMenu.add(jMenuItem3);

        aboutLabel.setMnemonic('A');
        aboutLabel.setText("About");
        helpMenu.add(aboutLabel);

        menu.add(helpMenu);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane90, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane101, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane102, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane103, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane104, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane105, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane106, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane107, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane108, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane109, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane110, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane111, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane112, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane113, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane114, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane115, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane116, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane117, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane118, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane119, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane120, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane121, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane122, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane123, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane124, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane125, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane126, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane127, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane128, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane129, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane130, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane131, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane132, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane133, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane134, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane135, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane136, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane137, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane138, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane139, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane140, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane141, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane142, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane143, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane144, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane145, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane146, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane147, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane148, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane149, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane150, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane151, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane152, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane153, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane154, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane155, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane156, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane157, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane158, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane159, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane160, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane161, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane162, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane90, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane89, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane87, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane86, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane85, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane84, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane83, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane82, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane91, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane92, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane93, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane94, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane95, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane96, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane97, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane98, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane100, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane101, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane102, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane103, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane104, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane105, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane106, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane107, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane108, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane109, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane110, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane111, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane112, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane113, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane114, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane115, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane116, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane117, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane118, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane119, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane120, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane121, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane122, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane123, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane124, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane125, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane126, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane127, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane128, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane129, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane130, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane131, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane132, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane133, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane134, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane135, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane136, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane137, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane138, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane139, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane140, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane141, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane142, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane143, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane144, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane145, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane146, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane147, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane148, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane149, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane150, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane151, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane152, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane153, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane156, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane157, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane158, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane159, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane160, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane161, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane162, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane154, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane155, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solve() {
                // TODO add your handling code here:
        // Declare and initialize a puzzle
        puzzle = new Puzzle(makeMappings());
        // Attempt to solve the puzzle
        HashMap<Integer, Integer> results = puzzle.solve();
        // Get the success as a boolean value
        Boolean success = (puzzle.countUnassignedCoordinates() == 0);
        // Set the value of each field to the values from the result hashmap
        HashMap<Integer, javax.swing.JTextPane> fields = getCoordFields();
        Set<Integer> fieldKeys = fields.keySet();
        for(int key : fieldKeys) {
            javax.swing.JTextPane field = fields.get(key);
            if(field.getText().isEmpty()) {
                try {
                    int number = results.get(key);
                    field.setText(String.valueOf(number));
                    field.setForeground(Color.blue);
                } catch (Exception ex) {
                    
                }
            }
        }
        if(!success) {
            statusLabel.setText("Failed to solve puzzle.");
        } else {
            statusLabel.setText("Successfully solved!");
        }
            successDialog.setVisible(true);
            okButton.requestFocusInWindow();
    }
    
    private void setTestState() {
        // Reset the stage
        reset();
        // Create a blank puzzle.
        puzzle = new Puzzle();
        // Execute the puzzle's test initializer.
        puzzle.initHardSamplePuzzle();
        // Get a reference too all fields
        HashMap<Integer, JTextPane> fields = getCoordFields();
        // For each co-ordinate with a number, 
        // Update the corresponding coordinate in the GUI.
        HashMap<Integer, Coordinate> coords = puzzle.getCoords();
        Set<Integer> coordKeys = coords.keySet();
        for(int key : coordKeys) {
            sudoku_solver.Logic.Number number = coords.get(key).getNumber();
            if (number != null) {
                fields.get(key).setText(String.valueOf(number.getNumber()));
            }
        }
    }
    
    private void clearAllFields() {
        HashMap<Integer, javax.swing.JTextPane> fields = getCoordFields();
        Set<Integer> fieldKeys = fields.keySet();
        for(int key : fieldKeys) {
            javax.swing.JTextPane field = fields.get(key);
            field.setText("");
        }
    }
    
    private void reset() {
        puzzle = null;
        clearAllFields();
    }
    
    private void initTestPuzzleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTestPuzzleMenuItemActionPerformed
        // TODO add your handling code here:
        setTestState();
    }//GEN-LAST:event_initTestPuzzleMenuItemActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_newGameMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        solve();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        successDialog.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void okButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okButtonKeyPressed
        // TODO add your handling code here:
        successDialog.setVisible(false);
    }//GEN-LAST:event_okButtonKeyPressed

    private boolean debug = false;
    private void debugMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugMenuItemActionPerformed
        // TODO add your handling code here:
        Puzzle.toggleDebug();
        if (debug) {
            debugMenuItem.setText("Toggle Debug (disable)");
        } else {
            debugMenuItem.setText("Toggle Debug (enable)");
        }
    }//GEN-LAST:event_debugMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    private HashMap<Integer, Integer> makeMappings() {
        // Declare a HashMap to hold the results
        HashMap<Integer, Integer> mappings = new HashMap<>();
        // Get a list of all fields
        HashMap<Integer, javax.swing.JTextPane> fields = getCoordFields();
        // Get the keys for the fields
        Set<Integer> fieldKeys = fields.keySet();
        // For each field in fields
        for(Integer key : fieldKeys) {
            javax.swing.JTextPane field = fields.get(key);
            // If the field is not blank,
            if (!field.getText().isEmpty()) {
                int number = Integer.parseInt(field.getText());
                mappings.put(key, number);
            }
        }
        return mappings;
    }
    
    /**
     * Gets a HashMap containing all fields
     * @return a HashMap containing all fields
     */
    private HashMap<Integer, javax.swing.JTextPane> getCoordFields() {
        HashMap<Integer, javax.swing.JTextPane> fields = new HashMap<>();
        fields.put(1, coord1);
        fields.put(2, coord2);
        fields.put(3, coord3);
        fields.put(4, coord4);
        fields.put(5, coord5);
        fields.put(6, coord6);
        fields.put(7, coord7);
        fields.put(8, coord8);
        fields.put(9, coord9);
        fields.put(10, coord10);
        fields.put(11, coord11);
        fields.put(12, coord12);
        fields.put(13, coord13);
        fields.put(14, coord14);
        fields.put(15, coord15);
        fields.put(16, coord16);
        fields.put(17, coord17);
        fields.put(18, coord18);
        fields.put(19, coord19);
        fields.put(20, coord20);
        fields.put(21, coord21);
        fields.put(22, coord22);
        fields.put(23, coord23);
        fields.put(24, coord24);
        fields.put(25, coord25);
        fields.put(26, coord26);
        fields.put(27, coord27);
        fields.put(28, coord28);
        fields.put(29, coord29);
        fields.put(30, coord30);
        fields.put(31, coord31);
        fields.put(32, coord32);
        fields.put(33, coord33);
        fields.put(34, coord34);
        fields.put(35, coord35);
        fields.put(36, coord36);
        fields.put(37, coord37);
        fields.put(38, coord38);
        fields.put(39, coord39);
        fields.put(40, coord40);
        fields.put(41, coord41);
        fields.put(42, coord42);
        fields.put(43, coord43);
        fields.put(44, coord44);
        fields.put(45, coord45);
        fields.put(46, coord46);
        fields.put(47, coord47);
        fields.put(48, coord48);
        fields.put(49, coord49);
        fields.put(50, coord50);
        fields.put(51, coord51);
        fields.put(52, coord52);
        fields.put(53, coord53);
        fields.put(54, coord54);
        fields.put(55, coord55);
        fields.put(56, coord56);
        fields.put(57, coord57);
        fields.put(58, coord58);
        fields.put(59, coord59);
        fields.put(60, coord60);
        fields.put(61, coord61);
        fields.put(62, coord62);
        fields.put(63, coord63);
        fields.put(64, coord64);
        fields.put(65, coord65);
        fields.put(66, coord66);
        fields.put(67, coord67);
        fields.put(68, coord68);
        fields.put(69, coord69);
        fields.put(70, coord70);
        fields.put(71, coord71);
        fields.put(72, coord72);
        fields.put(73, coord73);
        fields.put(74, coord74);
        fields.put(75, coord75);
        fields.put(76, coord76);
        fields.put(77, coord77);
        fields.put(78, coord78);
        fields.put(79, coord79);
        fields.put(80, coord80);
        fields.put(81, coord81);
        return fields;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutLabel;
    private javax.swing.JMenuItem autoGenMenuItem;
    private javax.swing.JMenu comingSoonMenu;
    private javax.swing.JTextPane coord1;
    private javax.swing.JTextPane coord10;
    private javax.swing.JTextPane coord11;
    private javax.swing.JTextPane coord12;
    private javax.swing.JTextPane coord13;
    private javax.swing.JTextPane coord14;
    private javax.swing.JTextPane coord15;
    private javax.swing.JTextPane coord16;
    private javax.swing.JTextPane coord17;
    private javax.swing.JTextPane coord18;
    private javax.swing.JTextPane coord19;
    private javax.swing.JTextPane coord2;
    private javax.swing.JTextPane coord20;
    private javax.swing.JTextPane coord21;
    private javax.swing.JTextPane coord22;
    private javax.swing.JTextPane coord23;
    private javax.swing.JTextPane coord24;
    private javax.swing.JTextPane coord25;
    private javax.swing.JTextPane coord26;
    private javax.swing.JTextPane coord27;
    private javax.swing.JTextPane coord28;
    private javax.swing.JTextPane coord29;
    private javax.swing.JTextPane coord3;
    private javax.swing.JTextPane coord30;
    private javax.swing.JTextPane coord31;
    private javax.swing.JTextPane coord32;
    private javax.swing.JTextPane coord33;
    private javax.swing.JTextPane coord34;
    private javax.swing.JTextPane coord35;
    private javax.swing.JTextPane coord36;
    private javax.swing.JTextPane coord37;
    private javax.swing.JTextPane coord38;
    private javax.swing.JTextPane coord39;
    private javax.swing.JTextPane coord4;
    private javax.swing.JTextPane coord40;
    private javax.swing.JTextPane coord41;
    private javax.swing.JTextPane coord42;
    private javax.swing.JTextPane coord43;
    private javax.swing.JTextPane coord44;
    private javax.swing.JTextPane coord45;
    private javax.swing.JTextPane coord46;
    private javax.swing.JTextPane coord47;
    private javax.swing.JTextPane coord48;
    private javax.swing.JTextPane coord49;
    private javax.swing.JTextPane coord5;
    private javax.swing.JTextPane coord50;
    private javax.swing.JTextPane coord51;
    private javax.swing.JTextPane coord52;
    private javax.swing.JTextPane coord53;
    private javax.swing.JTextPane coord54;
    private javax.swing.JTextPane coord55;
    private javax.swing.JTextPane coord56;
    private javax.swing.JTextPane coord57;
    private javax.swing.JTextPane coord58;
    private javax.swing.JTextPane coord59;
    private javax.swing.JTextPane coord6;
    private javax.swing.JTextPane coord60;
    private javax.swing.JTextPane coord61;
    private javax.swing.JTextPane coord62;
    private javax.swing.JTextPane coord63;
    private javax.swing.JTextPane coord64;
    private javax.swing.JTextPane coord65;
    private javax.swing.JTextPane coord66;
    private javax.swing.JTextPane coord67;
    private javax.swing.JTextPane coord68;
    private javax.swing.JTextPane coord69;
    private javax.swing.JTextPane coord7;
    private javax.swing.JTextPane coord70;
    private javax.swing.JTextPane coord71;
    private javax.swing.JTextPane coord72;
    private javax.swing.JTextPane coord73;
    private javax.swing.JTextPane coord74;
    private javax.swing.JTextPane coord75;
    private javax.swing.JTextPane coord76;
    private javax.swing.JTextPane coord77;
    private javax.swing.JTextPane coord78;
    private javax.swing.JTextPane coord79;
    private javax.swing.JTextPane coord8;
    private javax.swing.JTextPane coord80;
    private javax.swing.JTextPane coord81;
    private javax.swing.JTextPane coord9;
    private javax.swing.JMenuItem debugMenuItem;
    private javax.swing.JMenu devMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem initTestPuzzleMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane100;
    private javax.swing.JScrollPane jScrollPane101;
    private javax.swing.JScrollPane jScrollPane102;
    private javax.swing.JScrollPane jScrollPane103;
    private javax.swing.JScrollPane jScrollPane104;
    private javax.swing.JScrollPane jScrollPane105;
    private javax.swing.JScrollPane jScrollPane106;
    private javax.swing.JScrollPane jScrollPane107;
    private javax.swing.JScrollPane jScrollPane108;
    private javax.swing.JScrollPane jScrollPane109;
    private javax.swing.JScrollPane jScrollPane110;
    private javax.swing.JScrollPane jScrollPane111;
    private javax.swing.JScrollPane jScrollPane112;
    private javax.swing.JScrollPane jScrollPane113;
    private javax.swing.JScrollPane jScrollPane114;
    private javax.swing.JScrollPane jScrollPane115;
    private javax.swing.JScrollPane jScrollPane116;
    private javax.swing.JScrollPane jScrollPane117;
    private javax.swing.JScrollPane jScrollPane118;
    private javax.swing.JScrollPane jScrollPane119;
    private javax.swing.JScrollPane jScrollPane120;
    private javax.swing.JScrollPane jScrollPane121;
    private javax.swing.JScrollPane jScrollPane122;
    private javax.swing.JScrollPane jScrollPane123;
    private javax.swing.JScrollPane jScrollPane124;
    private javax.swing.JScrollPane jScrollPane125;
    private javax.swing.JScrollPane jScrollPane126;
    private javax.swing.JScrollPane jScrollPane127;
    private javax.swing.JScrollPane jScrollPane128;
    private javax.swing.JScrollPane jScrollPane129;
    private javax.swing.JScrollPane jScrollPane130;
    private javax.swing.JScrollPane jScrollPane131;
    private javax.swing.JScrollPane jScrollPane132;
    private javax.swing.JScrollPane jScrollPane133;
    private javax.swing.JScrollPane jScrollPane134;
    private javax.swing.JScrollPane jScrollPane135;
    private javax.swing.JScrollPane jScrollPane136;
    private javax.swing.JScrollPane jScrollPane137;
    private javax.swing.JScrollPane jScrollPane138;
    private javax.swing.JScrollPane jScrollPane139;
    private javax.swing.JScrollPane jScrollPane140;
    private javax.swing.JScrollPane jScrollPane141;
    private javax.swing.JScrollPane jScrollPane142;
    private javax.swing.JScrollPane jScrollPane143;
    private javax.swing.JScrollPane jScrollPane144;
    private javax.swing.JScrollPane jScrollPane145;
    private javax.swing.JScrollPane jScrollPane146;
    private javax.swing.JScrollPane jScrollPane147;
    private javax.swing.JScrollPane jScrollPane148;
    private javax.swing.JScrollPane jScrollPane149;
    private javax.swing.JScrollPane jScrollPane150;
    private javax.swing.JScrollPane jScrollPane151;
    private javax.swing.JScrollPane jScrollPane152;
    private javax.swing.JScrollPane jScrollPane153;
    private javax.swing.JScrollPane jScrollPane154;
    private javax.swing.JScrollPane jScrollPane155;
    private javax.swing.JScrollPane jScrollPane156;
    private javax.swing.JScrollPane jScrollPane157;
    private javax.swing.JScrollPane jScrollPane158;
    private javax.swing.JScrollPane jScrollPane159;
    private javax.swing.JScrollPane jScrollPane160;
    private javax.swing.JScrollPane jScrollPane161;
    private javax.swing.JScrollPane jScrollPane162;
    private javax.swing.JScrollPane jScrollPane82;
    private javax.swing.JScrollPane jScrollPane83;
    private javax.swing.JScrollPane jScrollPane84;
    private javax.swing.JScrollPane jScrollPane85;
    private javax.swing.JScrollPane jScrollPane86;
    private javax.swing.JScrollPane jScrollPane87;
    private javax.swing.JScrollPane jScrollPane88;
    private javax.swing.JScrollPane jScrollPane89;
    private javax.swing.JScrollPane jScrollPane90;
    private javax.swing.JScrollPane jScrollPane91;
    private javax.swing.JScrollPane jScrollPane92;
    private javax.swing.JScrollPane jScrollPane93;
    private javax.swing.JScrollPane jScrollPane94;
    private javax.swing.JScrollPane jScrollPane95;
    private javax.swing.JScrollPane jScrollPane96;
    private javax.swing.JScrollPane jScrollPane97;
    private javax.swing.JScrollPane jScrollPane98;
    private javax.swing.JScrollPane jScrollPane99;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JButton okButton;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JDialog successDialog;
    private javax.swing.JMenu toolsMenu;
    // End of variables declaration//GEN-END:variables
}
